### PR TITLE
Python kit improvements

### PR DESCRIPTION
**Pull request by IsaiahPressman**
Fixed bug where city_tile_count only incremented when new city_tiles were spawned, but never decremented if some cities died.

Fixed bug with text and sidetext functions which lacked the necessary single quotes around the message text.

QOL improvement by replacing ' ' with '_' for text function, because otherwise only the first word was displayed.

### CODE REVIEW

**Comment by StoneT2000** [comment]
Thanks for the fixes!

**Comment by StoneT2000** [comment]
Actually how did you verify the city_tile_count was not correct? It should be correct since every turn the starter kit will automatically reset that value to 0 before adding it back in

**Comment by IsaiahPressman** [comment]
Whoops, I seriously misread that portion of code. I was dealing with a bug with city counting and thought this was the problem. I reverted that change and left the message debug message fix.

**Comment by StoneT2000** [comment]
actually for message debugging we may handle this internally on the engine because other kits would have this issue too then.

**Comment by StoneT2000** [comment]
ok our fix will be like this

```
def text(x: int, y: int, message: str, fontsize: int = 16) -> str:
    return f"dt {x} {y} {fontsize} '{message}'"
```

so the parameters are first, then the arbitrarily long message is placed last.

I'll merge in what you have and make the fixes. Thanks!

**Pull request merged**
