### PR TITLE
validateCommand

### PR DESCRIPTION
**Pull request by LittleAlvinMaker**
major refactor to make validateCommand() MUCH more readable and less error-prone
(NOTE: the code will likely have a bug or two since I have no test harness)

### CODE REVIEW

**Comment by StoneT2000** [comment]
yeah this is a large change. i'm not too sure if we will ever merge this in. to test though, you can run

```
npm test
```

this will test nearly all of the validations.

**Comment by LittleAlvinMaker** [comment]
I have corrected the couple syntax errors and the flipped logical check, and it now passes all of the validation tests.

**Comment by StoneT2000** [comment]
just read through it, merged main branch to here. looks great, thanks!

**Comment by StoneT2000** [comment]
also this is fixed in the main branch now but we cannot use `+args[0]` is a integer parsing syntax as this allows floats to go through e.g. `+"1.23"` gives `1.23` which would cause some bugs.

**Pull request merged**
